- name: Initialize Kubernetes
  shell: |
    sudo kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --control-plane-endpoint={{ ansible_default_ipv4.address }} --apiserver-cert-extra-sans={{ ansible_default_ipv4.address }} --pod-network-cidr=10.0.0.0/16 --upload-certs

  register: output

- name: Storing Logs and Generated token for future purpose
  copy:
    content: "{{ output.stdout }}"
    dest: "/tmp/token"
- debug:
    msg: "{{ output.stdout }}"

- name: Generated token - 1.
  shell: sed -n 83,84p /tmp/token > /tmp/workertoken

#this coomand copy worker join command from Master server t Ansible controller
- name: Copy master token
  #shell: scp /tmp/workertoken aca@192.168.122.61:/tmp/join-worker-command.sh
  fetch:
    src: /tmp/workertoken
    dest: /tmp/join-worker-command.sh
    flat: yes

- name: create .kube folder
  shell: mkdir -p $HOME/.kube

- name: copy files to kube folder
  shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

- name: change ownership of the kube config
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config


- name: remove taints
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-

- name: Install Calico
  shell: |
    curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml -O
    kubectl apply -f calico.yaml





