




- name: Copy join command to worker nodes.
  copy:
    src: /tmp/join-worker-command.sh
    dest: /tmp/join-worker-command.sh


- name: Join the Worker nodes with the master.

  #command: sh /tmp/kubernetes_join_command
  command: sh /tmp/join-worker-command.sh
  register: joined_or_not
- debug:
    msg: "{{ joined_or_not.stdout }}"





